### ISSUE TITLE
How can i create a login in my app.js?

### ISSUE THREAD

**Issue by farhansyed9** [flovilmart/parse-express-cookie-session#7]
Currently im doing this:

`app.post('/login', function(req, res) {
Parse.User.logIn(req.body.username, req.body.password, {
success: function(user) {
// Do stuff after successful login.
console.log('user: ' + user);
res.redirect('/home');
},
error: function(user, error) {
// The login failed. Check error to see why.
console.log('error login');
res.redirect('/login');
}
});

});

app.get('/home',function(req, res){

if (Parse.User.current()) {
// No need to fetch the current user for querying Note objects.
var currentUser = Parse.User.current();
var sessionToken = currentUser.get('sessionToken');

console.log(sessionToken);
}
});`

It seems to log current user as nill everytime even tho it does say login is a success

**Comment by flovilmart** [comment]
Closing as deprecating the repository
