### ISSUE TITLE
_isNullOrUndefined is not defined

### ISSUE THREAD

**Issue by woodardj** [flovilmart/parse-express-cookie-session#8]
This library seems to be a lynchpin for a number of circulating threads on the `parse-server` repo…

If I send the option fetchUser to true, I'm getting the title-referenced error on line 138 when the true passes through the && condition.

I'm not sure where this method is intended to come from, but I can imagine what it looks like. What's your recommendation? Should I send a PR? Should I just replicate this whole codebase in my own?

**Comment by flovilmart** [comment]
this library need a complete revamp as we can't rely on the shared state of Parse.User.current();

**Comment by flovilmart** [comment]
Closing as deprecating the repository
